### ISSUE TITLE
Oleh Krehel / abo-abo 

### ISSUE THREAD

**Issue by agsdot** [tarsius/elisp-maintainers#10]
https://oremacs.com/2017/10/18/patreon/ - definitely another person considered to be an "elisp-maintainer".

His account should be added as well.

**Comment by tarsius** [comment]
I have added @abo-abo - was waiting for him to do it himself and then forgot about it.

And I have also added @NicolasPetton and @bzg. Could you all please double check the data and add other resources if desired.

**Comment by agsdot** [comment]
Cool. Thanks for adding @abo-abo to the list.

**Comment by tarsius** [comment]
I also wouldn't mind giving some of you commit access...

**Comment by abo-abo** [comment]
@tarsius Thanks.

**Comment by bzg** [comment]
@tarsius thanks a lot!

**Comment by NicolasPetton** [comment]
@tarsius thanks :)
