### ISSUE TITLE
Joining forces

### ISSUE THREAD

**Issue by tarsius** [tarsius/elisp-maintainers#11]
A similar effort was just announced on r/emacs (https://www.reddit.com/r/emacs/comments/83ehc1/support_your_favorite_editor_and_packages/). This is what I posted there in response:

> I have already started a similar effort at https://github.com/tarsius/elisp-maintainers. Please contribute to that instead of creating a new list.

> Your list makes it a little easier to map "my-favorite" to a page where you can send money, but `C-f my-favorite` isn't that much worse. My list is only intended as an intermediate step anyway, eventually there should be an Emacs package that lets users lookup such information. Maybe that could even be integrated into `package.el`.

/cc @tareefdev

It was also suggested that that list "be merged in the awesome emacs list". So /cc @emacs-tw. I think a good start would be to add a short paragraph with a link to this list at the top of the awesome emacs list.

**Comment by tarsius** [comment]
@tareefdev Also note that Gratipay has shut down, so those links don't do much good anymore.

**Comment by tareefdev** [comment]
Hi @tarsius Actually, your menu is much more comprehensive, by cross-checking the two lists, I think you just need to add the links for following packages: Markdown-mode, Leuven-theme, and Paypal link for Bastien Guerry.

It's much efficient to work on one list so I would be happy to contribute to your list in the future when I have new links.

**Comment by agsdot** [comment]
@tarsius , I saw your post on this github repository as well as your post on [reddit](https://www.reddit.com/r/emacs/comments/83ehc1/support_your_favorite_editor_and_packages/dvhfkaq/?context=1).

Recently, some changes were introduced on awesome-emacs. I'll ping and do an @tarius, on that repo to tag you on that commit.

Look at the wording. If you'd like it to be adjusted, provide a pull request to rephrase the wording.

**Comment by agsdot** [comment]
This repository is now referenced from awesome-emacs. That component of this issue was just addressed today.
